CREATE DATABASE edudocs
GO
USE edudocs
CREATE TABLE Users(id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()), password NVARCHAR(128) NOT NULL, login NVARCHAR(128) NOT NULL, lastName NVARCHAR(128), name NVARCHAR(128) NOT NULL, surname NVARCHAR(128) NOT NULL);



CREATE LOGIN Dev WITH PASSWORD = 'edSDD2002';
CREATE USER Dev for LOGIN Dev;
GRANT CONTROL To Dev;